---
name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Pip Packages
        run: pip install -r ./fs/code/requirements.txt -- mypy types-PyYAML

      - name: Lint
        run: mypy -- .

      - name: Test
        run: docker buildx build -- .
